FROM redhat/ubi8
RUN dnf module -y install go-toolset
RUN dnf install -y git
RUN git clone https://github.com/greeninja/patch-api.git
RUN cd patch-api; go build -o patch-api_rhel8 cmd/main.go
ENTRYPOINT [ "/bin/bash" ]